## 17 March 2025 - Exercises

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
exerciseDataOne = pd.read_excel("wfa_girls_0-to-13-weeks_zscores.xlsx")

In [3]:
exerciseDataOne

    Week       L       M        S  SD3neg  SD2neg  SD1neg  SD0  SD1  SD2  SD3
0      0  0.3809  3.2322  0.14171     2.0     2.4     2.8  3.2  3.7  4.2  4.8
1      1  0.2671  3.3388  0.14600     2.1     2.5     2.9  3.3  3.9  4.4  5.1
2      2  0.2304  3.5693  0.14339     2.3     2.7     3.1  3.6  4.1  4.7  5.4
3      3  0.2024  3.8352  0.14060     2.5     2.9     3.3  3.8  4.4  5.0  5.7
4      4  0.1789  4.0987  0.13805     2.7     3.1     3.6  4.1  4.7  5.4  6.1
5      5  0.1582  4.3476  0.13583     2.9     3.3     3.8  4.3  5.0  5.7  6.5
6      6  0.1395  4.5793  0.13392     3.0     3.5     4.0  4.6  5.2  6.0  6.8
7      7  0.1224  4.7950  0.13228     3.2     3.7     4.2  4.8  5.5  6.2  7.1
8      8  0.1065  4.9959  0.13087     3.3     3.8     4.4  5.0  5.7  6.5  7.3
9      9  0.0918  5.1842  0.12966     3.5     4.0     4.6  5.2  5.9  6.7  7.6
10    10  0.0779  5.3618  0.12861     3.6     4.1     4.7  5.4  6.1  6.9  7.8
11    11  0.0648  5.5295  0.12770     3.8     4.3     4.9  5.5  6.3  7.1  8.1
12    12  0.0525  5.6883  0.12691     3.9     4.4     5.0  5.7  6.5  7.3  8.3
13    13  0.0407  5.8393  0.12622     4.0     4.5     5.1  5.8  6.6  7.5  8.5

In [4]:
s = pd.Series([10,20,30,40,50],index=["a","b","c","d","e"])

In [5]:
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
p = pd.Series(["Serna","Ketsia","Tychique","Keren"])

In [8]:
p

0       Serna
1      Ketsia
2    Tychique
3       Keren
dtype: object

In [9]:
data = {"Name":["Serna","Ketsia","Keren","Tychique","Premi"],"Age":[22,8,17,20,8],"Salary":[0,0,0,0,0]}

In [10]:
data

{'Name': ['Serna', 'Ketsia', 'Keren', 'Tychique', 'Premi'],
 'Age': [22, 8, 17, 20, 8],
 'Salary': [0, 0, 0, 0, 0]}

In [11]:
df = pd.DataFrame(data)

In [12]:
df

       Name  Age  Salary
0     Serna   22       0
1    Ketsia    8       0
2     Keren   17       0
3  Tychique   20       0
4     Premi    8       0

In [13]:
df.to_csv("o.csv",index=False)

In [14]:
reading = pd.read_csv("o.csv")

In [15]:
reading

       Name  Age  Salary
0     Serna   22       0
1    Ketsia    8       0
2     Keren   17       0
3  Tychique   20       0
4     Premi    8       0

In [16]:
df.head()

       Name  Age  Salary
0     Serna   22       0
1    Ketsia    8       0
2     Keren   17       0
3  Tychique   20       0
4     Premi    8       0

In [17]:
df.tail(2)

       Name  Age  Salary
3  Tychique   20       0
4     Premi    8       0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Salary  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes

In [19]:
df.describe()

            Age  Salary
count   5.00000     5.0
mean   15.00000     0.0
std     6.63325     0.0
min     8.00000     0.0
25%     8.00000     0.0
50%    17.00000     0.0
75%    20.00000     0.0
max    22.00000     0.0

In [20]:
df["Name"]

0       Serna
1      Ketsia
2       Keren
3    Tychique
4       Premi
Name: Name, dtype: object

In [21]:
df[["Name","Age"]]

       Name  Age
0     Serna   22
1    Ketsia    8
2     Keren   17
3  Tychique   20
4     Premi    8

In [22]:
df[["Age","Name"]]

   Age      Name
0   22     Serna
1    8    Ketsia
2   17     Keren
3   20  Tychique
4    8     Premi